'use strict';
const $ = s => document.querySelector(s), KEY = 'homepage-studio-v1:' + location.pathname;
const AUTH_SESSION_KEY = 'homepage-studio-authenticated-v1';
const ADMIN_PASSWORD_HASH = '98ca704e9149ca345fd5ba5635fe62eaddccb3b1be85cef15a3567981b154aa0';
const CFG = {owner:'fancCoco',repo:'fancCoco.github.io',branch:'main'};
let data, baseData, sha=null, cfg={...CFG}, token='', active='profile', selected=0, busy=false, timer, storageOK=true;
let savedAt=null, noticeState=null, connectionError=null, deployedURL='';
function notice(key,params={},error=false){noticeState={key,params,error};deployedURL='';renderNotice()}
function reportError(e){notice(e.uiKey||'unexpected',e.uiKey?e.uiParams:{message:e.message},true)}
function renderNotice(){if(!noticeState)return;$('#notice').hidden=false;$('#notice').classList.toggle('error',noticeState.error);$('#notice').textContent=t(noticeState.key,noticeState.params);if(deployedURL){const a=document.createElement('a');a.href=deployedURL;a.textContent=' '+t('deployment');a.target='_blank';a.rel='noopener noreferrer';$('#notice').append(a)}}
function publicData(d){const out=structuredClone(d);for(const k of ['news','research','posts'])out[k]=out[k].filter(x=>x.status==='published');return out}
function preparePublishData(){const out=publicData(data),match=String(out.profile?.cv||'').match(/^data:application\/pdf;base64,([a-z0-9+/=]+)$/i);if(match)out.profile.cv='/CV.pdf';return {out,cvContent:match?.[1]||null}}
async function uploadCV(content){let fileSHA=null;try{fileSHA=(await api('/contents/CV.pdf?ref='+encodeURIComponent(cfg.branch))).sha}catch(e){if(e.uiKey!=='notFound')throw e}const body={message:'更新 CV 文件',content,branch:cfg.branch};if(fileSHA)body.sha=fileSHA;return api('/contents/CV.pdf',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
function renderSaveState(){$('#save-state').textContent=!storageOK?t('saveFailed'):savedAt?t('saved',{time:savedAt.toLocaleTimeString(language==='en'?'en-US':'zh-CN',{hour:'2-digit',minute:'2-digit'})}):t(data?'ready':'loading')}
function save(){try{localStorage.setItem(KEY,JSON.stringify({data,baseData,sha,cfg}));storageOK=true;savedAt=new Date()}catch{storageOK=false;notice('storageError',{},true)}renderSaveState()}
function current(){return active==='profile'?data.profile:data[active][selected]}
function field(key,label=key,type='text',help=''){const value=current()[key]||'';return `<label>${esc(t(label))}${type==='textarea'?`<textarea data-field="${key}" rows="${key==='body'?12:4}">${esc(value)}</textarea>`:`<input data-field="${key}" type="${type}" value="${esc(value)}">`}${help?`<span class="field-help">${esc(t(help))}</span>`:''}</label>`}
function imageField(key){return `${safeURL(current()[key],true)?`<img class="image-thumb" src="${esc(safeURL(current()[key],true))}" alt="${esc(t('currentImage'))}">`:''}${field(key,key,'text','imageHelp')}<label class="upload-label">${esc(t('upload'))}<input type="file" data-upload="${key}" accept="image/png,image/jpeg,image/webp"></label>`}
function cvField(){const value=current().cv||'',uploaded=/^data:application\/pdf;base64,/i.test(value);return `<label>${esc(t('cv'))}<input data-field="cv" type="url" value="${esc(uploaded?'/CV.pdf':value)}"><span class="field-help">${esc(t('cvHelp'))}</span></label>${uploaded?`<span class="field-help">${esc(t('cvUploaded'))}</span>`:''}<label class="upload-label">${esc(t('uploadCV'))}<input type="file" data-upload="cv" accept="application/pdf"></label>`}
function renderList(){$('#items').innerHTML=active==='profile'?'':data[active].map((x,i)=>`<button type="button" class="item ${i===selected?'selected':''}" data-select="${i}">${esc(x.title||t('untitled'))}<small>${esc(t(x.status==='draft'?'draftShort':'publicShort'))} / ${esc(x.date||x.year||'')}</small></button>`).join('')}
function renderEditor(){const x=current();renderList();if(!x){$('#editor').innerHTML=`<div class="empty">${esc(t('empty'))}</div>`;return}let html='';if(active==='profile')html=field('name')+field('nameZh')+field('role')+field('bio','bio','textarea','bioHelp')+field('affiliation')+field('location')+imageField('avatar')+field('email','email','email')+field('github','github','url')+field('scholar','scholar','url')+cvField();else{html=`<label>${esc(t('status'))}<select data-field="status"><option value="draft" ${x.status==='draft'?'selected':''}>${esc(t('draft'))}</option><option value="published" ${x.status==='published'?'selected':''}>${esc(t('public'))}</option></select></label>`+field('title');if(active==='news')html+=field('date','date','date')+field('url','url','url')+field('linkLabel');if(active==='research')html+='<div class="field-row">'+field('year')+field('venue')+'</div>'+field('category')+field('authors')+field('summary','summary','textarea')+field('abstract','abstract','textarea')+imageField('image')+field('paper','paper','url')+field('code','code','url')+field('project','project','url');if(active==='posts')html+='<div class="field-row">'+field('date','date','date')+field('tag')+'</div>'+field('body','body','textarea','bodyHelp');html+=`<div class="editor-actions"><button type="button" class="button" data-move="-1">${esc(t('moveUp'))}</button><button type="button" class="button" data-move="1">${esc(t('moveDown'))}</button><button type="button" class="button danger" id="delete-item">${esc(t('delete'))}</button></div>`}$('#editor').innerHTML=html}
function bindPreviewTheme(frame){const doc=frame.contentDocument;if(!doc)return;let theme=readTheme();applyTheme(theme,doc.documentElement);const button=doc.querySelector('#theme-toggle');updateThemeButton(button,theme);button?.addEventListener('click',()=>{theme=applyTheme(theme==='dark'?'light':'dark',doc.documentElement);updateThemeButton(button,theme);try{localStorage.setItem(THEME_KEY,theme)}catch{}})}
function preview(){const p=structuredClone(data);for(const k of ['news','research','posts'])for(const x of p[k])x.status='published';const frame=$('#preview'),pos=frame.contentWindow?.scrollY||0;frame.onload=()=>{if(pos)frame.contentWindow.scrollTo(0,pos);bindPreviewTheme(frame)};frame.srcdoc=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><base href="${esc(new URL('../',location.href).href)}"><link rel="stylesheet" href="style.css"></head><body>${renderSite(p,{preview:true})}</body></html>`}
function refresh(){renderEditor();preview()}
function sectionHeading(){$('#section-name').textContent=t(active);$('#section-help').textContent=t(active+'Help');$('#add').hidden=active==='profile'}
function choose(tab){active=tab;selected=0;sectionHeading();document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===active));refresh()}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='homepage-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function api(path,options={}){const r=await fetch('https://api.github.com/repos/'+encodeURIComponent(cfg.owner)+'/'+encodeURIComponent(cfg.repo)+path,{...options,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});if(!r.ok)throw uiError(({401:'unauthorized',403:'forbidden',404:'notFound',409:'conflict',422:'rejected'})[r.status]||'requestFailed',{status:r.status});return r.json()}
function decode(content){return new TextDecoder().decode(Uint8Array.from(atob(content.replace(/\s/g,'')),c=>c.charCodeAt(0)))}
function encode(content){let s='';for(const b of new TextEncoder().encode(content))s+=String.fromCharCode(b);return btoa(s)}
async function remote(){const r=await api('/contents/content/site.json?ref='+encodeURIComponent(cfg.branch));if(!r.content)throw uiError('fileTooLarge');return {sha:r.sha,data:validate(JSON.parse(decode(r.content)))}}
function busyState(on){busy=on;$('#publish').disabled=on;$('#confirm-publish').disabled=on;$('#connect-form button[type=submit]').disabled=on;$('#language').disabled=on}
async function passwordHash(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),byte=>byte.toString(16).padStart(2,'0')).join('')}
function setAuthenticated(authenticated){document.body.classList.toggle('locked',!authenticated);$('#auth-gate').hidden=authenticated;if(authenticated){$('#auth-password').value=''}else{setTimeout(()=>$('#auth-password').focus(),0)}}
function sessionAuthenticated(){try{return sessionStorage.getItem(AUTH_SESSION_KEY)==='1'}catch{return false}}
function rememberAuthentication(){try{sessionStorage.setItem(AUTH_SESSION_KEY,'1')}catch{}}
$('#auth-form').onsubmit=async e=>{e.preventDefault();const error=$('#auth-error'),input=$('#auth-password');error.hidden=true;try{if(await passwordHash(input.value.trim())!==ADMIN_PASSWORD_HASH){error.textContent=t('authInvalid');error.hidden=false;input.select();return}rememberAuthentication();setAuthenticated(true);await init()}catch{error.textContent=t('authUnavailable');error.hidden=false}};
async function init(){applyLanguage();$('#commit-message').value=t('defaultCommit');sectionHeading();try{const r=await fetch('../content/site.json',{cache:'no-store'});if(!r.ok)throw uiError('loadFailed');data=validate(await r.json());baseData=structuredClone(data);try{const cached=JSON.parse(localStorage.getItem(KEY)||'null');if(cached){data=validate(cached.data);baseData=validate(cached.baseData);sha=cached.sha;cfg=cached.cfg||CFG;notice('restored')}}catch{notice('invalidLocal',{},true)}for(const k of ['owner','repo','branch'])$('#connect-form').elements[k].value=cfg[k];refresh();renderSaveState()}catch(e){reportError(e);$('#save-state').textContent=t('loadFailedShort');$('#publish').disabled=true}}
function renderConnectionError(){$('#connect-error').textContent=connectionError?errorText(connectionError):'';if(connectionError?.uiKey==='remoteChanged'){const b=document.createElement('button');b.type='button';b.className='button';b.textContent=t('reloadRemote');b.onclick=async()=>{if(!confirm(t('reloadConfirm')))return;const f=$('#connect-form').elements;cfg={owner:f.owner.value.trim(),repo:f.repo.value.trim(),branch:f.branch.value.trim()};token=f.token.value.trim();try{const r=await remote();data=r.data;baseData=structuredClone(r.data);sha=r.sha;selected=0;save();refresh();$('#connected').textContent='✓';$('#connect-dialog').close();connectionError=null;notice('remoteLoaded')}catch(e){token='';$('#connected').textContent='○';reportError(e)}};$('#connect-error').append(document.createElement('br'),b)}}
function publishSummary(){if(!data)return;const {out}=preparePublishData(),count=['news','research','posts'].reduce((n,k)=>n+out[k].length,0);$('#publish-summary').textContent=t('publishSummary',{count,repo:cfg.owner+'/'+cfg.repo})}
$('#language').onchange=e=>{const previousDefault=t('defaultCommit');language=e.target.value==='en'?'en':'zh';try{localStorage.setItem(LANGUAGE_KEY,language)}catch{}applyLanguage();sectionHeading();renderSaveState();renderNotice();renderConnectionError();publishSummary();$('#preview-toggle').textContent=t($('.preview-panel').classList.contains('mobile')?'widePreview':'mobilePreview');if($('#commit-message').value===previousDefault)$('#commit-message').value=t('defaultCommit');if(data)renderEditor()};
$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b&&data)choose(b.dataset.tab)};
$('#editor').onsubmit=e=>e.preventDefault();
$('#editor').oninput=e=>{if(!e.target.dataset.field)return;current()[e.target.dataset.field]=e.target.value;save();renderList();clearTimeout(timer);timer=setTimeout(preview,180)};
$('#items').onclick=e=>{const b=e.target.closest('[data-select]');if(b){selected=Number(b.dataset.select);renderEditor()}};
$('#editor').onclick=e=>{const move=e.target.closest('[data-move]');if(move){const to=selected+Number(move.dataset.move);if(to>=0&&to<data[active].length){[data[active][selected],data[active][to]]=[data[active][to],data[active][selected]];selected=to;save();refresh()}}if(e.target.id==='delete-item'&&confirm(t('deleteConfirm'))){data[active].splice(selected,1);selected=Math.max(0,selected-1);save();refresh()}};
$('#add').onclick=()=>{const x={id:crypto.randomUUID(),title:'',status:'draft'},now=new Date(),date=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');if(active==='research')Object.assign(x,{year:String(now.getFullYear()),category:'Research',venue:'',authors:'',summary:'',abstract:'',image:'',paper:'',code:'',project:''});else Object.assign(x,{date,...(active==='posts'?{tag:'Notes',body:''}:{url:'',linkLabel:''})});data[active].unshift(x);selected=0;save();refresh();$('#editor input[data-field=title]').focus()};
$('#editor').onchange=async e=>{const key=e.target.dataset.upload,file=e.target.files?.[0];if(!key||!file)return;const item=current();try{if(key==='cv'){if((file.type&&file.type!=='application/pdf')||!file.name.toLowerCase().endsWith('.pdf')||file.size>15*1024*1024)throw uiError('pdfType');const reader=new FileReader(),value=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(uiError('pdfType'));reader.readAsDataURL(file)});if(typeof value!=='string'||!/^data:application\/pdf;base64,/i.test(value))throw uiError('pdfType');item.cv=value;save();refresh();notice('cvSaved');return}if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>15*1024*1024)throw uiError('imageType');const bitmap=await createImageBitmap(file),ratio=Math.min(1,1000/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();item[key]=canvas.toDataURL('image/jpeg',.78);save();refresh();notice('imageSaved')}catch(e){reportError(e)}};
$('#preview-toggle').onclick=()=>{$('.preview-panel').classList.toggle('mobile');$('#preview-toggle').textContent=t($('.preview-panel').classList.contains('mobile')?'widePreview':'mobilePreview')};
$('#export').onclick=()=>{if(data)download()};
$('#import').onchange=async e=>{try{if(!e.target.files[0])return;const imported=validate(JSON.parse(await e.target.files[0].text()));if(confirm(t('importConfirm'))){data=imported;selected=0;save();refresh();notice('imported')}}catch(err){notice('importError',{message:errorText(err)},true)}e.target.value=''};
$('#connection').onclick=()=>$('#connect-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#disconnect').onclick=()=>{token='';$('#connect-form').elements.token.value='';$('#connected').textContent='○';$('#connect-dialog').close();connectionError=null;notice('disconnected')};
$('#connect-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busyState(true);connectionError=null;$('#connect-error').textContent=t('verifying');const oldCfg=cfg,oldToken=token;try{const values=new FormData(e.target);cfg={owner:values.get('owner').trim(),repo:values.get('repo').trim(),branch:values.get('branch').trim()};token=values.get('token').trim();const r=await remote();if(JSON.stringify(r.data)!==JSON.stringify(baseData)){if(JSON.stringify(data)===JSON.stringify(baseData)){data=r.data;baseData=structuredClone(r.data);sha=r.sha;refresh()}else throw uiError('remoteChanged')}sha=r.sha;save();$('#connected').textContent='✓';$('#connect-dialog').close();$('#connect-error').textContent='';notice('connected',{repo:cfg.owner+'/'+cfg.repo})}catch(err){cfg=oldCfg;token=oldToken;connectionError=err;renderConnectionError()}finally{busyState(false)}};
$('#publish').onclick=()=>{if(!token){$('#connect-dialog').showModal();return}try{validate(data);if(!data.profile.name.trim())throw uiError('nameRequired');for(const k of ['news','research','posts'])for(const x of data[k])if(x.status==='published'&&!x.title.trim())throw uiError('titleRequired');if(new TextEncoder().encode(JSON.stringify(preparePublishData().out,null,2)).length>900000)throw uiError('payloadTooLarge');publishSummary();$('#publish-dialog').showModal()}catch(e){reportError(e)}};
$('#confirm-publish').onclick=async()=>{if(busy)return;busyState(true);$('#confirm-publish').textContent=t('submitting');try{const prepared=preparePublishData(),out=prepared.out,r=await remote();if(r.sha!==sha)throw uiError('conflict');if(prepared.cvContent)await uploadCV(prepared.cvContent);const result=await api('/contents/content/site.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:$('#commit-message').value.trim()||t('defaultCommit'),content:encode(JSON.stringify(out,null,2)+'\n'),sha,branch:cfg.branch})});data=structuredClone(out);sha=result.content.sha;baseData=structuredClone(out);save();refresh();$('#publish-dialog').close();notice('published');deployedURL='https://github.com/'+encodeURIComponent(cfg.owner)+'/'+encodeURIComponent(cfg.repo)+'/actions';renderNotice()}catch(e){$('#publish-dialog').close();reportError(e)}finally{busyState(false);$('#confirm-publish').textContent=t('confirmPublish')}};
window.addEventListener('beforeunload',e=>{if(busy||!storageOK){e.preventDefault();e.returnValue=''}});
applyLanguage();
if(sessionAuthenticated()){setAuthenticated(true);init()}else setAuthenticated(false);
