'use strict';
const $=s=>document.querySelector(s), KEY='homepage-studio-v1:'+location.pathname, CFG={owner:'fancCoco',repo:'fancCoco.github.io',branch:'main'};
const sections={profile:['个人资料','让大家认识你。从一段简洁的自我介绍开始。'],news:['最新动态','分享一个新进展，让关心你的人保持了解。'],research:['研究与项目','让每一项工作都有清晰的介绍和可访问的成果。'],posts:['文章与笔记','记录想法，分享发现。你的下一篇文章，从这里开始。']};
let data, baseData, sha=null, cfg={...CFG}, token='', active='profile', selected=0, busy=false, timer, storageOK=true;
function notice(text,error=false){$('#notice').hidden=false;$('#notice').classList.toggle('error',error);$('#notice').textContent=text}
function publicData(d){const out=structuredClone(d);for(const k of ['news','research','posts'])out[k]=out[k].filter(x=>x.status==='published');return out}
function save(){try{localStorage.setItem(KEY,JSON.stringify({data,baseData,sha,cfg}));storageOK=true;$('#save-state').textContent='草稿已保存到本机 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}catch{storageOK=false;$('#save-state').textContent='本机保存失败，请导出备份';notice('浏览器存储空间不足或不可用。当前更改仍在页面中，请先导出备份再关闭页面。',true)}}
function current(){return active==='profile'?data.profile:data[active][selected]}
function field(key,label,type='text',help=''){const value=current()[key]||'';return `<label>${label}${type==='textarea'?`<textarea data-field="${key}" rows="${key==='body'?12:4}">${esc(value)}</textarea>`:`<input data-field="${key}" type="${type}" value="${esc(value)}">`}${help?`<span class="field-help">${help}</span>`:''}</label>`}
function imageField(key,label){return `${safeURL(current()[key],true)?`<img class="image-thumb" src="${esc(safeURL(current()[key],true))}" alt="当前图片">`:''}${field(key,label,'text','可粘贴完整图片网址，也可在下方上传。清空此处可移除图片。')}<label class="upload-label">上传图片（自动压缩）<input type="file" data-upload="${key}" accept="image/png,image/jpeg,image/webp"></label>`}
function renderList(){if(active==='profile'){$('#items').innerHTML='';return}$('#items').innerHTML=data[active].map((x,i)=>`<button type="button" class="item ${i===selected?'selected':''}" data-select="${i}">${esc(x.title||'未命名内容')}<small>${x.status==='draft'?'草稿 · 仅本机':'公开 · 发布时上传'} / ${esc(x.date||x.year||'')}</small></button>`).join('')}
function renderEditor(){const x=current();renderList();if(!x){$('#editor').innerHTML='<div class="empty">还没有内容。点击「新建内容」开始。</div>';return}let html='';if(active==='profile')html=field('name','姓名 / 英文名')+field('nameZh','中文名（可选）')+field('role','身份 / 研究领域')+field('bio','自我介绍','textarea','换行分段；支持 **加粗**。')+field('affiliation','学校 / 实验室 / 团队')+field('location','所在城市')+imageField('avatar','头像网址')+field('email','公开邮箱','email')+field('github','GitHub 网址','url')+field('scholar','Google Scholar 网址','url')+field('cv','简历 PDF 网址','url');else{html=`<label>发布状态<select data-field="status"><option value="draft" ${x.status==='draft'?'selected':''}>草稿 · 仅保存在本机</option><option value="published" ${x.status==='published'?'selected':''}>公开 · 下次发布时上传</option></select></label>`+field('title','标题');if(active==='news')html+=field('date','日期','date')+field('url','相关链接（可选）','url')+field('linkLabel','链接文字（可选）');if(active==='research')html+='<div class="field-row">'+field('year','年份')+field('venue','会议 / 期刊 / 类型')+'</div>'+field('category','分类')+field('authors','作者')+field('summary','简短介绍','textarea')+field('abstract','详细摘要','textarea')+imageField('image','项目图片网址')+field('paper','论文网址','url')+field('code','代码网址','url')+field('project','项目网址','url');if(active==='posts')html+='<div class="field-row">'+field('date','日期','date')+field('tag','标签')+'</div>'+field('body','正文','textarea','支持换行分段、# 标题、## 小标题、**加粗**。暂不解析其他 Markdown 或 HTML。');html+='<div class="editor-actions"><button type="button" class="button" data-move="-1">上移 ↑</button><button type="button" class="button" data-move="1">下移 ↓</button><button type="button" class="button danger" id="delete-item">删除这条内容</button></div>'}$('#editor').innerHTML=html}
function preview(){const p=structuredClone(data);for(const k of ['news','research','posts'])for(const x of p[k])x.status='published';const frame=$('#preview'), pos=frame.contentWindow?.scrollY||0;frame.onload=()=>{if(pos)frame.contentWindow.scrollTo(0,pos)};frame.srcdoc=`<!doctype html><html lang="zh-CN"><head><meta name="viewport" content="width=device-width,initial-scale=1"><base href="${esc(new URL('../',location.href).href)}"><link rel="stylesheet" href="style.css"></head><body>${renderSite(p,{preview:true})}</body></html>`}
function refresh(){renderEditor();preview()}
function choose(tab){active=tab;selected=0;$('#section-name').textContent=sections[active][0];$('#section-help').textContent=sections[active][1];$('#add').hidden=active==='profile';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===active));refresh()}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='homepage-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function api(path,options={}){const r=await fetch('https://api.github.com/repos/'+encodeURIComponent(cfg.owner)+'/'+encodeURIComponent(cfg.repo)+path,{...options,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});if(!r.ok){const messages={401:'令牌无效或已过期，请重新连接。',403:'访问被拒绝：请检查令牌的 Contents 读写权限、仓库授权或 API 速率限制。',404:'找不到仓库、分支或内容文件，请检查连接设置。',409:'仓库内容已被其他地方更新。为避免覆盖，请导出备份，再断开并重新载入。',422:'提交未通过校验，请检查分支保护规则及写入权限。'};throw Error(messages[r.status]||'GitHub 请求失败（'+r.status+'），请稍后重试。')}return r.json()}
function decode(content){return new TextDecoder().decode(Uint8Array.from(atob(content.replace(/\s/g,'')),c=>c.charCodeAt(0)))}
function encode(content){let s='';for(const b of new TextEncoder().encode(content))s+=String.fromCharCode(b);return btoa(s)}
async function remote(){const r=await api('/contents/content/site.json?ref='+encodeURIComponent(cfg.branch));if(!r.content)throw Error('内容文件过大，无法读取。请改用外部图片网址，或从仓库下载备份。');return {sha:r.sha,data:validate(JSON.parse(decode(r.content)))}}
function busyState(on){busy=on;$('#publish').disabled=on;$('#confirm-publish').disabled=on;$('#connect-form button[type=submit]').disabled=on}
async function init(){try{const r=await fetch('../content/site.json',{cache:'no-store'});if(!r.ok)throw Error('无法加载主页数据');data=validate(await r.json());baseData=structuredClone(data);try{const cached=JSON.parse(localStorage.getItem(KEY)||'null');if(cached){data=validate(cached.data);baseData=validate(cached.baseData);sha=cached.sha;cfg=cached.cfg||CFG;notice('已恢复此浏览器的本地草稿。连接 GitHub 后会检查远程版本，避免覆盖其他设备的更新。')}}catch{notice('本地备份无法读取，已加载当前主页内容。',true)}for(const k of ['owner','repo','branch'])$('#connect-form').elements[k].value=cfg[k];refresh();$('#save-state').textContent='可以开始编辑 · 更改自动保存'}catch(e){notice(e.message+'。请刷新重试。',true);$('#save-state').textContent='加载失败';$('#publish').disabled=true}}
$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b&&data)choose(b.dataset.tab)};
$('#editor').onsubmit=e=>e.preventDefault();
$('#editor').oninput=e=>{if(!e.target.dataset.field)return;current()[e.target.dataset.field]=e.target.value;save();renderList();clearTimeout(timer);timer=setTimeout(preview,180)};
$('#items').onclick=e=>{const b=e.target.closest('[data-select]');if(b){selected=Number(b.dataset.select);renderEditor()}};
$('#editor').onclick=e=>{const move=e.target.closest('[data-move]');if(move){const to=selected+Number(move.dataset.move);if(to>=0&&to<data[active].length){[data[active][selected],data[active][to]]=[data[active][to],data[active][selected]];selected=to;save();refresh()}}if(e.target.id==='delete-item'&&confirm('删除这条内容？本机草稿将移除，主页会在下次发布后更新。')){data[active].splice(selected,1);selected=Math.max(0,selected-1);save();refresh()}};
$('#add').onclick=()=>{const x={id:crypto.randomUUID(),title:'',status:'draft'};if(active==='research')Object.assign(x,{year:String(new Date().getFullYear()),category:'Research',venue:'',authors:'',summary:'',abstract:'',image:'',paper:'',code:'',project:''});else Object.assign(x,{date:new Date().toLocaleDateString('en-CA'),...(active==='posts'?{tag:'随笔',body:''}:{url:'',linkLabel:''})});data[active].unshift(x);selected=0;save();refresh();$('#editor input[data-field=title]').focus()};
$('#editor').onchange=async e=>{const key=e.target.dataset.upload,file=e.target.files?.[0];if(!key||!file)return;const item=current();try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('请选择小于 15MB 的 PNG、JPG 或 WebP 图片。');const bitmap=await createImageBitmap(file), ratio=Math.min(1,1000/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();item[key]=canvas.toDataURL('image/jpeg',.78);save();refresh();notice('图片已压缩并加入本地草稿。发布时会一同上传。')}catch(err){notice(err.message,true)}};
$('#preview-toggle').onclick=()=>{$('.preview-panel').classList.toggle('mobile');$('#preview-toggle').textContent=$('.preview-panel').classList.contains('mobile')?'切换宽屏预览':'切换手机预览'};
$('#export').onclick=()=>{if(data)download()};
$('#import').onchange=async e=>{try{if(!e.target.files[0])return;const imported=validate(JSON.parse(await e.target.files[0].text()));if(confirm('用备份替换当前本地内容？建议先导出当前备份。')){data=imported;selected=0;save();refresh();notice('备份已导入本机，尚未发布。')}}catch(err){notice('导入失败：'+err.message,true)}e.target.value=''};
$('#connection').onclick=()=>$('#connect-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#disconnect').onclick=()=>{token='';$('#connect-form').elements.token.value='';$('#connected').textContent='○';$('#connect-dialog').close();notice('已断开连接。草稿仍保存在当前浏览器。')};
$('#connect-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busyState(true);$('#connect-error').textContent='正在验证…';const oldCfg=cfg,oldToken=token;try{const values=new FormData(e.target);cfg={owner:values.get('owner').trim(),repo:values.get('repo').trim(),branch:values.get('branch').trim()};token=values.get('token').trim();const r=await remote();if(JSON.stringify(r.data)!==JSON.stringify(baseData)){if(JSON.stringify(data)===JSON.stringify(baseData)){data=r.data;baseData=structuredClone(r.data);sha=r.sha;refresh()}else{throw Error('远程内容与本地草稿的基础版本不同。请先导出完整备份，再点击“重新加载远程内容”，然后重新导入或整理你的修改。')}}sha=r.sha;save();$('#connected').textContent='✓';$('#connect-dialog').close();$('#connect-error').textContent='';notice('已连接 '+cfg.owner+'/'+cfg.repo+'。现在可以发布更新。')}catch(err){cfg=oldCfg;token=oldToken;$('#connect-error').textContent=err.message; if(err.message.startsWith('远程内容')){const b=document.createElement('button');b.type='button';b.className='button';b.textContent='重新加载远程内容';b.onclick=async()=>{if(!confirm('这会替换本地草稿。请确认已经导出备份。'))return;const f=$('#connect-form').elements;cfg={owner:f.owner.value.trim(),repo:f.repo.value.trim(),branch:f.branch.value.trim()};token=f.token.value.trim();try{const r=await remote();data=r.data;baseData=structuredClone(r.data);sha=r.sha;selected=0;save();refresh();$('#connected').textContent='✓';$('#connect-dialog').close();notice('已加载远程内容并连接 GitHub。')}catch(x){token='';notice(x.message,true)}};$('#connect-error').append(document.createElement('br'),b)}}finally{busyState(false)}};
$('#publish').onclick=()=>{if(!token){$('#connect-dialog').showModal();return}try{validate(data);if(!data.profile.name.trim())throw Error('请填写姓名。');for(const k of ['news','research','posts'])for(const x of data[k])if(x.status==='published'&&!x.title.trim())throw Error('请为所有公开内容填写标题。');const out=publicData(data);if(new TextEncoder().encode(JSON.stringify(out)).length>900000)throw Error('内容和图片总量超过 900KB，请减少图片大小或改用外部图片网址。');const count=['news','research','posts'].reduce((n,k)=>n+out[k].length,0);$('#publish-summary').textContent=`将发布个人资料及 ${count} 条公开内容到 ${cfg.owner}/${cfg.repo}。`;$('#publish-dialog').showModal()}catch(err){notice(err.message,true)}};
$('#confirm-publish').onclick=async()=>{if(busy)return;busyState(true);$('#confirm-publish').textContent='正在提交…';try{const out=publicData(data), r=await remote();if(r.sha!==sha)throw Error('仓库已有新版本，已停止发布以免覆盖。请导出备份，然后重新连接并加载远程内容。');const result=await api('/contents/content/site.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:$('#commit-message').value.trim()||'更新个人主页内容',content:encode(JSON.stringify(out,null,2)+'\n'),sha,branch:cfg.branch})});sha=result.content.sha;baseData=structuredClone(out);save();$('#publish-dialog').close();notice('内容已提交到 GitHub。主页将在 GitHub Pages 部署完成后更新，通常需要几分钟。');const a=document.createElement('a');a.href='https://github.com/'+encodeURIComponent(cfg.owner)+'/'+encodeURIComponent(cfg.repo)+'/actions';a.textContent=' 查看部署进度 ↗';a.target='_blank';a.rel='noopener noreferrer';$('#notice').append(a)}catch(err){$('#publish-dialog').close();notice(err.message,true)}finally{busyState(false);$('#confirm-publish').textContent='确认发布'}};
window.addEventListener('beforeunload',e=>{if(busy||!storageOK){e.preventDefault();e.returnValue=''}});init();
